### ISSUE TITLE
LicenseCompareHelper: Apache-1.0 & 1.1 license texts published by Apache not recognised

### ISSUE THREAD

**Issue by pmonks** [spdx/Spdx-Java-Library#184]
The [license text for `Apache-1.1` published by Apache](https://www.apache.org/licenses/LICENSE-1.1) is not being recognised by `org.spdx.utility.compare.LicenseCompareHelper.isStandardLicenseWithinText()`.

Note: tested with Spdx-Java-Library v1.1.7.

**Comment by pmonks** [comment]
Note sure if this is useful (given the extraneous prefix and suffix text in the source text), but the "difference message" in the `DifferenceDescription` object returned from `org.spdx.utility.compare.LicenseCompareHelper.isTextStandardLicense()` says:

```
Variable text rule combined-bullet-Clause5 did not match the compare text starting at line #38 column #1 "5" while processing rule var: combined-bullet-Clause5.  Last optional text was not found due to the optional difference:
	Normal text of license does not match starting at line #1 column #4 "an" when comparing to template text "Apache License 1.1

"
```

**Comment by pmonks** [comment]
I'm seeing the same behaviour with the [`Apache-1.0` text published by Apache ](https://github.com/spdx/Spdx-Java-Library/issues/184) too.

**Comment by sdheh** [comment]
This could be the same problem of dealing with multiple spaces when matching with a var rule as in #219 and #218. There are multiple spaces in point 5 and it has a var rule.

**Comment by sdheh** [comment]
I verified that replacing all new lines and multiple spaces by single spaces results in the Apache-1.1 text to be correctly identified but not the Apache-1.0 text.
The Apache 1.0 text differs in bullet 5:
"appear in their **names**, without prior" instead of "appear in their **name**, without prior" so this is a bug in the template.

**Comment by goneall** [comment]
This should now be fixed with PR #221

**Comment by pmonks** [comment]
> This should now be fixed with PR #221

Minor clarification: this is still failing, but that's due to https://github.com/spdx/license-list-XML/issues/2259 (i.e. PR #221 has fixed any Spdx-Java-Library specific problems involved in this behaviour).
